<div class="manickAdminPins">
    <div class="links">
        <p class="marker">Manick</p>
        <a href="#">Pin this page</a>
        <a href="#">Page</a>
        <a href="#">Page</a>
        <a href="#">Page</a>
        <a href="#">Page</a>
        <a href="#">Page</a>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Manick_AdminPins/js/adminPins": {}
        }
    }
</script>
